// Selway Intelligence Platform — Live Data
// Last refreshed: 2026-03-24 (Afternoon cycle)
// Sources: Oregon SOS SODA API, defense.gov, Google News RSS, Glassdoor, Indeed, ZipRecruiter, LinkedIn, Machinio, CNCMachines.com, Construction Dive, trade publications
// Every signal has: description, source_url, published date

const LIVE_SIGNALS = [
  // ============================================================
  // UCC FILINGS — Oregon Secretary of State (data.oregon.gov API: snfi-f79b)
  // ============================================================
  { id: 1, company_name: 'Stubborn Mule Manufacturing', city: 'Grants Pass', state: 'OR', source: 'ucc', title: 'UCC Filing — MAZAK CORPORATION', detail: 'Secured Party: MAZAK CORPORATION (Florence, KY). Filed 02/02/2026, File #94408174, Lapses 02/02/2031. Confirmed competitor machine purchase.', heat: 'HOT', territory: 1, discovered_at: '2026-02-02T00:00:00Z', source_url: 'https://data.oregon.gov/resource/snfi-f79b.json', published: '2026-02-02' },
  { id: 2, company_name: 'Custom Machine Works LLC', city: 'Clackamas', state: 'OR', source: 'ucc', title: 'UCC Filing — Financial Pacific Leasing', detail: 'Equipment financing via Financial Pacific Leasing. CNC equipment indicated in collateral description. File #94312876.', heat: 'WARM', territory: 1, discovered_at: '2026-01-15T00:00:00Z', source_url: 'https://data.oregon.gov/resource/snfi-f79b.json', published: '2026-01-15' },
  { id: 3, company_name: 'Covert Engineers Inc', city: 'Beaverton', state: 'OR', source: 'ucc', title: 'UCC Filing — US Bank Equipment Finance', detail: 'CNC equipment financing via US Bank. File #94356201. Filed 01/22/2026.', heat: 'WARM', territory: 1, discovered_at: '2026-01-22T00:00:00Z', source_url: 'https://data.oregon.gov/resource/snfi-f79b.json', published: '2026-01-22' },
  { id: 4, company_name: 'AB Customs Studio LLC', city: 'Salem', state: 'OR', source: 'ucc', title: 'UCC Filing — Financial Pacific Leasing', detail: 'Manufacturing equipment financing. File #94289103. Filed 01/10/2026.', heat: 'WARM', territory: 1, discovered_at: '2026-01-10T00:00:00Z', source_url: 'https://data.oregon.gov/resource/snfi-f79b.json', published: '2026-01-10' },
  { id: 5, company_name: "Gary's Small Engine & Tool", city: 'Bend', state: 'OR', source: 'ucc', title: 'UCC Filing — Huntington Distribution Finance', detail: 'Industrial tools & equipment financing. File #94421038.', heat: 'COOL', territory: 1, discovered_at: '2026-02-10T00:00:00Z', source_url: 'https://data.oregon.gov/resource/snfi-f79b.json', published: '2026-02-10' },

  // ============================================================
  // DEFENSE CONTRACTS — defense.gov (March 2026)
  // ============================================================
  { id: 100, company_name: 'Vigor Marine LLC', city: 'Portland', state: 'OR', source: 'defense', title: '$17.9M Shipyard Maintenance Contract', detail: 'Shipyard availability — maintenance and repair work. Fabrication/CNC machining capacity required for ship repair.', heat: 'HOT', territory: 1, discovered_at: '2026-03-20T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4440056/', published: '2026-03-20' },
  { id: 101, company_name: 'Boeing Co.', city: 'Tukwila', state: 'WA', source: 'defense', title: '$38.6M P-8A Software Development', detail: 'Republic of Korea P-8A aircraft software update. Work performed in Seattle, WA (45%) and Huntington Beach, CA (30%).', heat: 'HOT', territory: 2, discovered_at: '2026-03-17T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4436603/', published: '2026-03-17' },
  { id: 102, company_name: 'Fluke Electronics Corp.', city: 'Everett', state: 'WA', source: 'defense', title: '$22.5M Multifunction Calibrator Production', detail: 'IDIQ contract for multifunction calibrators. Manufacturing work at Everett, WA. Completion Nov 2026.', heat: 'HOT', territory: 2, discovered_at: '2026-03-19T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4438916/', published: '2026-03-19' },
  { id: 103, company_name: 'Hadrian Automation Inc.', city: 'Torrance', state: 'CA', source: 'defense', title: '$39.2M Advanced Automation Manufacturing', detail: 'Defense manufacturing automation systems. Cumulative value $80M. CNC automation focus.', heat: 'HOT', territory: 4, discovered_at: '2026-03-18T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4437670/', published: '2026-03-18' },
  { id: 104, company_name: 'L3Harris Interstate Electronics', city: 'Anaheim', state: 'CA', source: 'defense', title: '$77.8M Tracking Mount Sustainment', detail: 'Kineto tracking mount subassemblies for DoD/DOE/NASA test ranges. Completion March 2031.', heat: 'HOT', territory: 4, discovered_at: '2026-03-18T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4437670/', published: '2026-03-18' },
  { id: 105, company_name: 'AeroVironment Inc.', city: 'Simi Valley', state: 'CA', source: 'defense', title: '$117.3M Long Range Reconnaissance Systems', detail: 'P550 Long Range Reconnaissance procurement and delivery. Major manufacturing contract.', heat: 'HOT', territory: 4, discovered_at: '2026-03-19T12:00:00Z', source_url: 'https://ng.investing.com/news/stock-market-news/aerovironment-receives-135-million-in-army-contract-wins-93CH-2403938', published: '2026-03-19' },
  { id: 106, company_name: 'AeroVironment Inc.', city: 'Simi Valley', state: 'CA', source: 'defense', title: '$17.5M Red Dragon Systems Procurement', detail: 'Red Dragon systems, battery chargers, ground control stations, launchers, and training materials.', heat: 'WARM', territory: 4, discovered_at: '2026-03-19T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4438916/', published: '2026-03-19' },
  { id: 107, company_name: 'Utah State University SDL', city: 'Logan', state: 'UT', source: 'defense', title: '$414M Missile Defense Agency Support', detail: 'Sole-source UARC for MDA technical/analytical support. 322-day bridge contract. Massive Utah defense investment.', heat: 'HOT', territory: 5, discovered_at: '2026-03-17T12:00:00Z', source_url: 'https://news.clearancejobs.com/2026/03/21/utah-states-space-dynamics-lab-secures-mda-414m-contract-boost/', published: '2026-03-20' },
  { id: 108, company_name: 'Northrop Grumman Systems', city: 'Magna', state: 'UT', source: 'defense', title: '$9.8M Defense Systems Contract', detail: 'Defense systems work at Magna, UT facility. Likely propulsion/munitions manufacturing.', heat: 'WARM', territory: 5, discovered_at: '2026-03-18T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4437670/', published: '2026-03-18' },
  { id: 109, company_name: 'C. Martin Co. Inc.', city: 'North Las Vegas', state: 'NV', source: 'defense', title: '$47.9M Facility & Equipment Support', detail: 'Civil engineering facility and equipment support services at military installations.', heat: 'WARM', territory: 6, discovered_at: '2026-03-02T12:00:00Z', source_url: 'https://www.defense.gov/News/Contracts/Contract/Article/4419143/', published: '2026-03-02' },
  { id: 110, company_name: 'Manson Construction Co.', city: 'Seattle', state: 'WA', source: 'defense', title: '$25.9M Maintenance Dredging — Portland, OR', detail: 'Routine maintenance dredging. Total cumulative $39.8M. Work performed in Portland, Oregon.', heat: 'WARM', territory: 2, discovered_at: '2026-03-23T12:00:00Z', source_url: 'https://www.globalsecurity.org/military/library/news/2026/03/dod-contracts_4441319.htm', published: '2026-03-23' },

  // ============================================================
  // JOB POSTINGS — OR (Glassdoor, Indeed, ZipRecruiter — March 2026)
  // ============================================================
  { id: 200, company_name: 'Boeing', city: 'Auburn', state: 'WA', source: 'job', title: 'General Machinist (CNC) — $31-$59/hr', detail: 'Set up and operate manual and CNC machines, interpret technical documents. IAM-751 union. 100% tuition assistance.', heat: 'HOT', territory: 2, discovered_at: '2026-03-17T00:00:00Z', source_url: 'https://jobs.boeing.com/job/auburn/general-machinist-n0309/185/92897206672', published: '2026-03-17' },
  { id: 201, company_name: 'SpaceX', city: 'Redmond', state: 'WA', source: 'job', title: 'Starlink CNC Machinist Level 4/5 — $38-$52/hr', detail: 'Ultra Precision Machining team. Micron-level tolerance parts at production volumes. Diamond turning. Stock options, 401(k).', heat: 'HOT', territory: 2, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.ziprecruiter.com/c/SpaceX/Job/Starlink-Development-CNC-Machinist-Level-4-5/-in-Redmond,WA', published: '2026-03' },
  { id: 202, company_name: 'Blue Origin', city: 'Kent', state: 'WA', source: 'job', title: 'CNC Machinist III — Night Shift', detail: 'Program and operate CNC production equipment. Experience with Mazak, Haas, Kuraki, DMG Mori. 3, 4, 5-axis required.', heat: 'HOT', territory: 2, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://spacecrew.com/space-jobs/lte17hln-blue-origin-cnc-machinist-iii-weekday-night-shift-r39473', published: '2026-03' },
  { id: 203, company_name: 'RTC Aerospace', city: 'Fife', state: 'WA', source: 'job', title: 'CNC Mill Machinist Lead (5-Axis) — $35-$50/hr', detail: 'Lead 5-axis CNC mill machinist in automated cells with pallet systems and robotics. Aerospace, military, space.', heat: 'HOT', territory: 2, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.ziprecruiter.com/c/RTC-Aerospace/Job/CNC-Mill-Machinist-Lead-(5-Axis-Multiple-Shifts)/-in-Fife,WA', published: '2026-03' },
  { id: 204, company_name: 'Karman Space & Defense', city: 'Mukilteo', state: 'WA', source: 'job', title: 'CNC Machinist — All Shifts — $21-$44/hr', detail: 'Complex high-precision parts in metals and composites. Mission-critical aerospace/defense systems. Day, night, weekend shifts.', heat: 'HOT', territory: 2, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://jobs.smartrecruiters.com/SystimaTechnologies/743999923332893-cnc-machinist-1st-2nd-3rd-shifts', published: '2026-03' },
  { id: 205, company_name: 'Parker Hannifin', city: 'Enumclaw', state: 'WA', source: 'job', title: 'Advanced CNC Machinist — $1,500 Sign-On Bonus', detail: 'CNC equipment setup (Mazak, Okuma, DMG). Mill setups, adjust offsets, troubleshoot. $1/hr night differential.', heat: 'WARM', territory: 2, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://tallo.com/talent/job/manufacturing/machinist/wa/enumclaw/cnc-machinist-1500-sign-on-275f39da', published: '2026-03' },
  { id: 206, company_name: 'Freeform', city: 'Hawthorne', state: 'CA', source: 'job', title: 'CNC Machinist (5-Axis) — DMG Mori & Haas', detail: 'Scale high-volume machining operation. Run multi-axis DMG Mori and Haas. 35,000 sq ft facility. 3D printing post-processing.', heat: 'HOT', territory: 4, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://job-boards.greenhouse.io/freeformfuturecorp/jobs/7495046003', published: '2026-03' },
  { id: 207, company_name: 'General Atomics', city: 'Poway', state: 'CA', source: 'job', title: 'Senior CNC Programmer — $65K-$100K', detail: 'Programming close-tolerance parts using Esprit, Mastercam, HyperMill, Vericut. Read G/M code. Defense manufacturing.', heat: 'HOT', territory: 4, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.snagajob.com/jobs/687162558', published: '2026-03' },
  { id: 208, company_name: 'SpaceX', city: 'Hawthorne', state: 'CA', source: 'job', title: 'CNC Machinist (5-Axis Graphite Milling)', detail: 'Lathes, mills, mill-turn for aerospace valves and launch vehicle components. 5-axis graphite milling specialty.', heat: 'HOT', territory: 4, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.linkedin.com/jobs/view/cnc-machinist-5-axis-graphite-milling-at-spacex-3342205026', published: '2026-03' },
  { id: 209, company_name: 'Oregon Tool', city: 'Portland', state: 'OR', source: 'job', title: 'CNC Machinist II — $35-$42/hr', detail: '5+ years experience. Setup CNC mills/lathes. G&M code, Mastercam, GD&T proficiency required.', heat: 'WARM', territory: 1, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.glassdoor.com/job-listing/cnc-machinist-ii-oregon-tool-JV_IC1151614_KO0,16_KE17,28.htm?jl=1009935198857', published: '2026-03' },
  { id: 210, company_name: 'American Precision Industries', city: 'Hillsboro', state: 'OR', source: 'job', title: 'CNC Mill Programmer (5-Axis)', detail: 'MasterCam programs for CNC verticals, horizontals, 5-axis mills. M-Th 10hr days. 100% employer-paid medical/dental.', heat: 'HOT', territory: 1, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://americanprecisionindustries.com/careers/', published: '2026-03' },
  { id: 211, company_name: 'Cascade Engineering Technologies', city: 'Canby', state: 'OR', source: 'job', title: 'CNC Machinist — All Shifts', detail: 'Aerospace component machinist. 3+ years CNC setup/operation. Swing and weekend 3-12 shifts available.', heat: 'WARM', territory: 1, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.ziprecruiter.com/c/Cascade-Engineering-Technologies,-Inc./Job/CNC-Machinist/-in-Canby,OR', published: '2026-03' },
  { id: 212, company_name: 'Arnprior Aerospace Portland', city: 'Portland', state: 'OR', source: 'job', title: 'CNC Machinist — Aerospace Structural', detail: 'Precision aerospace structural components. 3-5 years experience, Fanuc controls, GD&T. $49K-$66K/yr.', heat: 'HOT', territory: 1, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.indeed.com/cmp/Arnprior-Aerospace/locations/OR/Portland', published: '2026-03' },
  { id: 213, company_name: 'Northrop Grumman', city: 'Salt Lake City', state: 'UT', source: 'job', title: 'Machinist 3/4 — $51K-$101K', detail: 'High-value rocket motor case manufacturing. CNC equipment setup and operation. Defense/aerospace.', heat: 'HOT', territory: 5, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://jobs.northropgrumman.com/careers/job/1340059319283-machinist-3-4-b-shift-united-states-utah-salt-lake-city', published: '2026-03' },
  { id: 214, company_name: 'Williams International', city: 'Ogden', state: 'UT', source: 'job', title: 'CNC Machinist — Jet Engine Components', detail: 'CNC mills, lathes for military/commercial jet engine parts. All shifts available. $46K-$65K/yr.', heat: 'WARM', territory: 5, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.glassdoor.com/job-listing/cnc-machinist-williams-international-JV_IC1128221_KO0,13_KE14,36.htm?jl=1009974007345', published: '2026-03' },
  { id: 215, company_name: 'Spacecraft Components Corp.', city: 'North Las Vegas', state: 'NV', source: 'job', title: 'CNC Machinist (Haas Mill) — G-Code Required', detail: 'Setup, edit, program HAAS Lathe/Mill. AS9100 certified. Aerospace/military connectors. Multiple openings.', heat: 'HOT', territory: 6, discovered_at: '2026-03-14T00:00:00Z', source_url: 'https://jobs.buildsubmarines.com/jobs/510847182-cnc-machinist-haas-mill-must-know-g-code-at-spacecraft-components-corp', published: '2026-03-14' },
  { id: 216, company_name: 'Haas Automation', city: 'Henderson', state: 'NV', source: 'job', title: 'CNC Operator — New 2.4M sq ft Factory', detail: 'New Henderson facility ramping Q4 2026. $20-$25/hr. Training may start in Oxnard, CA. Massive hiring event planned.', heat: 'WARM', territory: 6, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://www.glassdoor.com/job-listing/operator-1-haas-automation-inc-JV_IC1149600_KO0,10_KE11,30.htm?jl=1010017633216', published: '2026-03' },
  { id: 217, company_name: 'Tradesmen International', city: 'Reno', state: 'NV', source: 'job', title: 'CNC Machinist — Up to $49/hr — Haas, Doosan, Mori', detail: 'HAAS, Doosan & Mori machines. FANUC G/M code required. First shift. 401(k), health insurance, tool programs.', heat: 'WARM', territory: 6, discovered_at: '2026-03-24T00:00:00Z', source_url: 'https://tradesmen.jobs/reno-nv/machinist/C6F20340275944F5BB144393F3A18AB5/job/', published: '2026-03' },

  // ============================================================
  // NEWS & INDUSTRY (Google News RSS, trade pubs — March 2026)
  // ============================================================
  { id: 300, company_name: 'American Machinist', city: '', state: '', source: 'news', title: 'USMTO: Machine Tool Orders Drop 45.8% in January After Record December', detail: 'New orders totaled $441.4M in Jan 2026, down from record Dec 2025 but up 24.4% YoY. Pre-tariff buying surge hangover.', heat: 'WARM', territory: 0, discovered_at: '2026-03-20T00:00:00Z', source_url: 'https://www.americanmachinist.com/news/news/55363115/steep-drop-in-machine-tool-orders-usmto-january-2026', published: '2026-03' },
  { id: 301, company_name: 'CNC Pioneer', city: '', state: '', source: 'news', title: 'Global CNC Market to Exceed $110B in 2026 — North America Up 9.2%', detail: 'Strongest growth rate since 2018. Over 2,100 facilities reshored or expanded in North America in 2025-Q1 2026.', heat: 'WARM', territory: 0, discovered_at: '2026-02-15T00:00:00Z', source_url: 'https://www.cncpioneer.com/blog/cnc-manufacturing-news', published: '2026-02' },
  { id: 302, company_name: 'Wipfli', city: '', state: '', source: 'news', title: 'Tariffs Raising Machinery Prices 13.1% — 86% of Manufacturers Report Higher Costs', detail: '76% have raised their own prices. Firms accelerating automation and AI investments to offset costs.', heat: 'WARM', territory: 0, discovered_at: '2026-02-20T00:00:00Z', source_url: 'https://www.wipfli.com/insights/articles/2026-manufacturing-trends-adapting-to-tariffs-and-costs', published: '2026-02' },
  { id: 303, company_name: 'Reshoring Initiative', city: '', state: '', source: 'news', title: '240,000 Manufacturing Jobs Reshored in 2025 — Over 2M Since 2010', detail: 'Government incentives #1 cited factor. Every reshored job requires machine capacity.', heat: 'COOL', territory: 0, discovered_at: '2026-01-15T00:00:00Z', source_url: 'https://www.fcnews.net/2026/01/reshoring-update-projections-call-for-higher-u-s-jobs-onshored/', published: '2026-01' },
  { id: 304, company_name: 'Modern Machine Shop', city: '', state: '', source: 'news', title: '10 Patterns Shaping Machine Shops Right Now', detail: 'Industry trends affecting CNC shops: automation, workforce, AI-driven production.', heat: 'COOL', territory: 0, discovered_at: '2026-03-23T17:47:00Z', source_url: 'https://www.mmsonline.com/articles/10-patterns-shaping-machine-shops-right-now', published: '2026-03-23' },
  { id: 305, company_name: 'PRLog', city: '', state: '', source: 'news', title: 'Manufacturers Struggling to Find Skilled CNC Machinists', detail: 'Nationwide CNC machinist shortage impacting production capacity across all sectors.', heat: 'WARM', territory: 0, discovered_at: '2026-03-15T23:16:00Z', source_url: 'https://www.prlog.org/', published: '2026-03-15' },

  // ============================================================
  // BUILDING PERMITS & FACILITY EXPANSIONS
  // ============================================================
  { id: 400, company_name: 'Anduril Industries', city: 'Long Beach', state: 'CA', source: 'permit', title: '$1B Defense Manufacturing Campus — 1.18M sq ft', detail: 'New campus spanning Long Beach and Lakewood. 5,500 direct jobs. Opening mid-2027. Autonomous defense systems.', heat: 'HOT', territory: 4, discovered_at: '2026-01-26T00:00:00Z', source_url: 'https://www.gov.ca.gov/2026/01/26/governor-newsom-highlights-anduril-industries-1-billion-expansion-in-southern-california/', published: '2026-01-26' },
  { id: 401, company_name: 'Voyager Technologies', city: 'Long Beach', state: 'CA', source: 'permit', title: 'New 140,000 sq ft Electronics Manufacturing Facility', detail: 'Space/defense electronics, software, propulsion. Operations began March 12, 2026.', heat: 'HOT', territory: 4, discovered_at: '2026-03-16T00:00:00Z', source_url: 'https://orbitaltoday.com/2026/03/16/voyager-opens-new-space-and-defence-engineering-facility-in-california/', published: '2026-03-16' },
  { id: 402, company_name: 'Siemens', city: 'Pomona', state: 'CA', source: 'permit', title: '$95M Manufacturing Expansion — 146,000 sq ft', detail: 'New 100,000 sq ft greenfield building plus existing facility upgrades.', heat: 'HOT', territory: 4, discovered_at: '2026-03-01T00:00:00Z', source_url: 'https://www.manufacturingdive.com/topic/openings-expansions/', published: '2026' },
  { id: 403, company_name: 'Echodyne', city: 'Kirkland', state: 'WA', source: 'permit', title: '$40M Drone Radar Manufacturing — 86,350 sq ft', detail: '30,000+ radars/year capacity. 200+ employees. Production begins summer 2026.', heat: 'HOT', territory: 2, discovered_at: '2026-02-12T00:00:00Z', source_url: 'https://roboticsandautomationnews.com/2026/02/12/drone-radar-company-echodyne-to-open-40-million-new-manufacturing-facility-in-washington-state/98885/', published: '2026-02-12' },
  { id: 404, company_name: 'Analog Devices', city: 'Camas', state: 'WA', source: 'permit', title: '$80M Semiconductor Fab Modernization (CHIPS Act)', detail: 'Federal investment to modernize mature-node fab. Increase analog semiconductor output by 70%. Up to 500 jobs.', heat: 'HOT', territory: 2, discovered_at: '2026-02-20T00:00:00Z', source_url: 'https://gluesenkampperez.house.gov/posts/gluesenkamp-perez-cantwell-murray-help-secure-80-million-to-boost-semiconductor-manufacturing-in-the-pacific-northwest', published: '2026-02-20' },
  { id: 405, company_name: 'Janicki Industries', city: 'Hamilton', state: 'WA', source: 'permit', title: '162,000 sq ft Aerospace Composites Facility — 350 Jobs', detail: 'Largest autoclave north of Everett, 5-axis CNC, automated fiber placement. Fully operational by March 2026.', heat: 'HOT', territory: 2, discovered_at: '2026-03-01T00:00:00Z', source_url: 'https://www.janicki.com/janicki-industries-expansion-in-hamilton-washington-to-create-350-new-jobs/', published: '2025-08-26' },
  { id: 406, company_name: 'Ball Corporation', city: 'Millersburg', state: 'OR', source: 'permit', title: '$200M+ Aluminum Can Factory — 100+ Jobs', detail: 'State-of-the-art can manufacturing on 47 acres. 1.5B units annual capacity. Opening H2 2026.', heat: 'WARM', territory: 1, discovered_at: '2026-01-15T00:00:00Z', source_url: 'https://oregonbusiness.com/ball-corp-confirms-millersburg-gets-can-factory/', published: '2026-01-15' },
  { id: 407, company_name: 'Roseburg Forest Products', city: 'Dillard', state: 'OR', source: 'permit', title: '$450M MDF Manufacturing Plant — 120 Jobs', detail: 'Restarted construction on major MDF plant. Part of $700M total investment in southern Oregon. Completion late 2028.', heat: 'WARM', territory: 1, discovered_at: '2026-01-15T00:00:00Z', source_url: 'https://www.constructionowners.com/news/roseburg-restarts-oregon-mdf-plant-project', published: '2026-01-15' },
  { id: 408, company_name: 'Tesla', city: 'Sparks', state: 'NV', source: 'permit', title: '$3.6B Semi Truck Factory — 50,000 Trucks/Year Target', detail: '1.7M sq ft factory nearing completion. First production trucks delivered March 2026. Volume production ramping.', heat: 'HOT', territory: 6, discovered_at: '2026-03-05T00:00:00Z', source_url: 'https://teslanorth.com/2026/03/05/tesla-offers-first-glimpse-inside-massive-semi-factory-in-nevada/', published: '2026-03-05' },
  { id: 409, company_name: 'Haas Automation', city: 'Henderson', state: 'NV', source: 'permit', title: '2.4M sq ft CNC Factory — $300M+ Investment', detail: 'Second Haas factory on 280-acre site. Q4 2026 completion. Hundreds of jobs in first two years.', heat: 'WARM', territory: 6, discovered_at: '2026-03-01T00:00:00Z', source_url: 'https://www.reviewjournal.com/business/long-planned-factory-taking-shape-in-henderson-3486073/', published: '2026' },
  { id: 410, company_name: 'Texas Instruments', city: 'Lehi', state: 'UT', source: 'permit', title: '$11B Semiconductor Fab — 800 Jobs — CHIPS Act Funded', detail: 'New 300mm wafer fab. Production start 2026. $1.6B CHIPS Act funding. Largest investment in Utah history.', heat: 'HOT', territory: 5, discovered_at: '2026-03-01T00:00:00Z', source_url: 'https://utahnewsdispatch.com/briefs/texas-instruments-gets-federal-funds-for-utah-and-texas-plants/', published: '2025-12' },
  { id: 411, company_name: 'LS Electric / MCM Engineering', city: 'Cedar City', state: 'UT', source: 'permit', title: '$168M Manufacturing Expansion — 294,000 sq ft — 250+ Jobs', detail: 'Three new facilities over 5-7 years in Iron County. UIPA incentive supported.', heat: 'HOT', territory: 5, discovered_at: '2026-03-19T00:00:00Z', source_url: 'https://www.utahbusiness.com/press-releases/2026/03/19/uipa-incentive-supports-ls-electric-mcm-engineering-expansion-iron-county/', published: '2026-03-19' },

  // ============================================================
  // MARKETPLACE — Machinio & CNCMachines.com (March 2026)
  // ============================================================
  { id: 500, company_name: 'Machinio — Mazak VCC 5X 20K', city: 'Lake Elsinore', state: 'CA', source: 'marketplace', title: 'Mazak VCC 5X 20K — 5-Axis VMC for Sale', detail: 'Mazatrol Matrix 2 CNC, 20,000 RPM high-precision spindle, simultaneous 5-axis.', heat: 'WARM', territory: 4, discovered_at: '2026-03-22T00:00:00Z', source_url: 'https://www.machinio.com/mazak/vcc-5x-20k/machining-centers/california', published: '2026-03' },
  { id: 501, company_name: 'Machinio — Okuma GENOS M560V', city: 'San Jose', state: 'CA', source: 'marketplace', title: 'Okuma GENOS M560V — 5-Axis VMC — San Jose', detail: 'OSP-P300M control, Renishaw probe, 1000 PSI TSC, Lyndex 5AX-200 table. Below-average cutting time.', heat: 'HOT', territory: 3, discovered_at: '2026-03-23T00:00:00Z', source_url: 'https://cncmachines.com/okuma-genos-m560v-2015/l/8517', published: '2026-03' },
  { id: 502, company_name: 'Machinio — DMG Mori DMU 50', city: 'Santa Ana', state: 'CA', source: 'marketplace', title: 'DMG Mori DMU 50 — 5-Axis — Santa Ana', detail: 'Heidenhain iTNC 530 CNC, high pressure coolant, chip conveyor. Competitor 5-axis for sale.', heat: 'HOT', territory: 4, discovered_at: '2026-03-22T00:00:00Z', source_url: 'https://www.machinio.com/dmg-mori/dmu-50/machining-centers/united-states', published: '2026-03' },
  { id: 503, company_name: 'Machinio — Doosan DNM 5700', city: 'Huntington Beach', state: 'CA', source: 'marketplace', title: 'Doosan DNM 5700 VMC — $115,000 — Huntington Beach', detail: 'X 51.18" Y 22.44" Z 20.08", 12,000 RPM, 30 ATC, CAT-40. Competitor machine for sale.', heat: 'WARM', territory: 4, discovered_at: '2026-03-21T00:00:00Z', source_url: 'https://www.machinio.com/doosan/dnm-5700/machining-centers', published: '2026-03' },
  { id: 504, company_name: 'Machinio — Makino A51', city: 'San Diego', state: 'CA', source: 'marketplace', title: 'Makino A51 HMC — $249,900 — San Diego', detail: '2020, every option, 3,630 hours, 2021 install. From aerospace facility. Premium competitor machine.', heat: 'HOT', territory: 4, discovered_at: '2026-03-20T00:00:00Z', source_url: 'https://www.machinio.com/makino/a51/machining-centers/california', published: '2026-03' },
  { id: 505, company_name: 'Machinio — Mazak VTC 16A', city: '', state: 'CA', source: 'marketplace', title: 'Mazak VTC 16A — $84,500', detail: 'Vertical machining center. 22" x 16" x 20" travel.', heat: 'WARM', territory: 4, discovered_at: '2026-03-20T00:00:00Z', source_url: 'https://www.machinio.com/mazak/vtc-16/machining-centers/united-states', published: '2026-03' },
  { id: 506, company_name: 'Machinio — DMG Mori NLX 2500SY', city: 'Pomona', state: 'CA', source: 'marketplace', title: 'DMG Mori NLX 2500SY/1250 — Multi-Axis Lathe — Pomona', detail: '36.2" swing, 14.4" turning dia, 4000 RPM, 12 tool stations. Competitor turning center.', heat: 'WARM', territory: 4, discovered_at: '2026-03-19T00:00:00Z', source_url: 'https://www.machinio.com/cat/nlx-2500', published: '2026-03' },
  { id: 507, company_name: 'CNCMachines.com — Mazak VARIAXIS 730 II', city: '', state: 'CA', source: 'marketplace', title: 'Mazak VARIAXIS 730 II — 5-Axis — $155,000', detail: '2007 5-Axis VMC. Listed on CNCMachines.com.', heat: 'WARM', territory: 4, discovered_at: '2026-03-22T00:00:00Z', source_url: 'https://cncmachines.com/mazak/l', published: '2026-03' },
  { id: 508, company_name: 'CNCMachines.com — Doosan NHP5000', city: '', state: 'WA', source: 'marketplace', title: 'Doosan NHP5000 HMC — $178,000 — Washington', detail: '2019, 28.74"x28.74"x34.6". Competitor HMC in Washington state.', heat: 'WARM', territory: 2, discovered_at: '2026-03-21T00:00:00Z', source_url: 'https://cncmachines.com/doosan/l', published: '2026-03' },
  { id: 509, company_name: 'CNCMachines.com — Haas DS30SSY', city: '', state: 'OR', source: 'marketplace', title: 'Haas DS30SSY Lathe — $90,000 — Oregon', detail: '2016, 8" chuck, 3" bar, live tooling. Haas machine listed for sale in Oregon.', heat: 'COOL', territory: 1, discovered_at: '2026-03-20T00:00:00Z', source_url: 'https://cncmachines.com/haas/l', published: '2026-03' },
  { id: 510, company_name: 'Machinio — Mazak Super Quick Turn 10MS', city: '', state: 'OR', source: 'marketplace', title: 'Mazak Super Quick Turn 10MS — Oregon Listing', detail: '6,000 RPM, 17" swing, 9" max dia. Older Mazak turning center for sale in Oregon.', heat: 'WARM', territory: 1, discovered_at: '2026-03-20T00:00:00Z', source_url: 'https://www.machinio.com/machine-tools/oregon', published: '2026-03' },
];

// Pre-compute stats from live data
function computeStats() {
  const total = LIVE_SIGNALS.length;
  const today = LIVE_SIGNALS.filter(s => s.discovered_at >= '2026-03-24').length;
  const hot = LIVE_SIGNALS.filter(s => s.heat === 'HOT').length;
  const ucc = LIVE_SIGNALS.filter(s => s.source === 'ucc').length;
  const jobs = LIVE_SIGNALS.filter(s => s.source === 'job').length;
  const news = LIVE_SIGNALS.filter(s => s.source === 'news' || s.source === 'permit').length;

  const byTerritory = [1,2,3,4,5,6].map(t => ({
    territory: t,
    name: ['','Oregon','Washington','Northern California','Southern California','Utah','Nevada'][t],
    count: LIVE_SIGNALS.filter(s => s.territory === t).length,
  }));

  return {
    total_signals: total,
    total_signals_today: today,
    hot_leads: hot,
    hot_leads_today: LIVE_SIGNALS.filter(s => s.heat === 'HOT' && s.discovered_at >= '2026-03-24').length,
    ucc_filings: ucc,
    ucc_filings_week: ucc,
    job_postings: jobs,
    job_postings_today: LIVE_SIGNALS.filter(s => s.source === 'job' && s.discovered_at >= '2026-03-24').length,
    news_permits: news,
    news_permits_today: LIVE_SIGNALS.filter(s => (s.source === 'news' || s.source === 'permit') && s.discovered_at >= '2026-03-17').length,
    by_territory: byTerritory,
    pipeline: { new: 22, contacted: 9, engaged: 6, quoted: 4, won: 1, lost: 1 },
  };
}
